# -*- coding: utf-8 -*-
"""IMDB_vectorisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128cdj9Kol1bi-waNVs2age_rGRhaYFf7
"""

print("Antas")

import pandas as pd
import numpy as np

df = pd.read_csv('/content/imdb_text_preprocessed.csv')
print(df.info())
print(df.head())

import ast
text_str = df['review'][2]
text_list = np.array(ast.literal_eval(text_str))
print(text_list.reshape(-1, 1))

#ohe impolementaion
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()

sample_text_ohe = onehotencoder.fit_transform(text_list.reshape(-1, 1))
print(sample_text_ohe.toarray())

#n-grams implementation(uni and bi)

from sklearn.feature_extraction.text import CountVectorizer
cv_uni = CountVectorizer()
sample_text_uni = cv_uni.fit_transform(text_list)
print(sample_text_uni.toarray())

print(cv_uni.vocabulary_)

#bigram
#sample text for bi gram
def convert_to_string(text_list):
  sample_text_str = ""
  for words in text_list:
    sample_text_str = sample_text_str + " "+ words
  return sample_text_str

for i in range(0,3):
  doc_li = []
  text_str_bi = df['review'][i]
  text_list_bi = np.array(ast.literal_eval(text_str))
  sample_text_str = convert_to_string(text_list)
  doc_li.append(sample_text_str)

cv_bi = CountVectorizer(ngram_range=(2, 2))
sample_text_bi = cv_bi.fit_transform(doc_li)
print(sample_text_bi.toarray())

print(cv_bi.vocabulary_)

#tf-idf implementation
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

sample_text_tfidf = tfidf.fit_transform(doc_li)
print(sample_text_tfidf.toarray())

#vectorising the whole df using tf-idf

all_docs=[]
for review in df['review']:
  text_list = np.array(ast.literal_eval(review))
  sample_text_str = convert_to_string(text_list)
  all_docs.append(sample_text_str)

tfidf_all = TfidfVectorizer()
final_df_all = tfidf_all.fit_transform (all_docs)

print(final_df_all.shape)

#generating a sample for 1000 rows to convert it to tfidf vector

df_10000 = df.head(10000).copy()
df_10000['tfidf_vector'] = list(final_df_all[:10000].toarray())

print(df_10000.head())

row0 = final_df_all[0].toarray().flatten()
nonzero_idx = row0.nonzero()[0]
print([(tfidf_all.get_feature_names_out()[i], row0[i]) for i in nonzero_idx])

df_10000.to_csv('IMDB_tf-idf.csv', index=False)

