# -*- coding: utf-8 -*-
"""text_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19F-CK0CHMixgb0hLM7a6hQr84e1Hd9Jk
"""

print("Antas")

import pandas as pd
df = pd.read_csv("/content/df_use_csv.csv")

#lowering the chars
df['overview'] = df['overview'].str.lower()

import string
string.punctuation

def remove_punctuation(text):
  return text.translate(str.maketrans('','',string.punctuation))

df['overview'] = df['overview'].apply(lambda text: remove_punctuation(text))

from textblob import TextBlob

def Correct_spelling(text):
  return str(TextBlob(text).correct())

df['overview'] = df['overview'].apply(lambda text: Correct_spelling(text))

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stpw = stopwords.words('english')

print(stpw)

def remove_stpw(text):
  new_text =[]
  for word in text.split():
    if word in stpw:
      continue
    new_text.append(word)
  return " ".join(new_text)

df['overview'] = df['overview'].apply(lambda text: remove_stpw(text))

df['overview'][6]

from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

df['overview'] = df['overview'].apply(lambda text: word_tokenize(text))

df['overview'][6]

import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

Lemmatizer = WordNetLemmatizer()

def lemitize(tokenise_list):
  new_text = []
  for word in tokenise_list:
    new_text.append(Lemmatizer.lemmatize(word, pos ='v'))
  return new_text

df['overview'] = df['overview'].apply(lambda text: lemitize(text))
df['overview'][6]

df.to_csv('text_preprocessed.csv', index= False)